[package]
name = "tiger"
version = "0.1.0"
authors = ["Tony Solomonik <tony.solomonik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2"
lazy_static = "1.4.0"
clap = "2.33.0"