[package]
name = "tiger"
version = "0.1.0"
authors = ["Tony Solomonik <tony.solomonik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-arena = "2.0.1"
clap = "3.0.0-beta.1"